In [1]:
import pandas as pd

In [2]:
tree = pd.read_csv("trees.csv", sep=";")

In [3]:
tree.head()

GEOPOINT  ARRONDISSEMENT       GENRE        ESPECE  \
0   (48.857140829, 2.29533455314)               7     Maclura      pomifera   
1  (48.8685686134, 2.31331809304)               8  Calocedrus     decurrens   
2  (48.8768191638, 2.33210374339)               9  Pterocarya  fraxinifolia   
3  (48.8373323894, 2.40776275516)              12      Celtis     australis   
4  (48.8341842636, 2.46130493573)              12     Quercus       petraea   

        FAMILLE  ANNEE PLANTATION  HAUTEUR  CIRCONFERENCE  \
0      Moraceae            1935.0     13.0            NaN   
1  Cupressaceae            1854.0     20.0          195.0   
2  Juglandaceae            1862.0     22.0          330.0   
3   Cannabaceae            1906.0     16.0          295.0   
4      Fagaceae            1784.0     30.0          430.0   

                                             ADRESSE               NOM COMMUN  \
0  Quai Branly, avenue de La Motte-Piquet, avenue...       Oranger des Osages   
1  Cours-la-Reine, avenue Franklin-D.-Roosevelt, ...           Cèdre à encens   
2                           Place d'Estienne-d'Orves     Pérocarya du Caucase   
3                                27, boulevard Soult  Micocoulier de Provence   
4                            route ronde des Minimes             Chêne rouvre   

  VARIETE  OBJECTID                               NOM_EV  
0     NaN         6               Parc du Champs de Mars  
1     NaN        11            Jardin des Champs Elysées  
2     NaN        14               Square Etienne d'Orves  
3     NaN        16            Avenue 27 boulevard Soult  
4     NaN        19  Bois de Vincennes (lac des minimes)

In [4]:
len(tree.ARRONDISSEMENT.value_counts())

17

In [5]:
tree[["GENRE","HAUTEUR"]].groupby("GENRE").max()

HAUTEUR
GENRE                  
Acer               16.0
Aesculus           30.0
Ailanthus          35.0
Alnus              16.0
Araucaria           9.0
Broussonetia       12.0
Calocedrus         20.0
Catalpa            15.0
Cedrus             30.0
Celtis             16.0
Corylus            20.0
Davidia            12.0
Diospyros          14.0
Eucommia           12.0
Fagus              30.0
Fraxinus           30.0
Ginkgo             33.0
Gymnocladus        10.0
Juglans            28.0
Liriodendron       35.0
Maclura            13.0
Magnolia           12.0
Paulownia          20.0
Pinus              30.0
Platanus           45.0
Pterocarya         30.0
Quercus            31.0
Robinia            11.0
Sequoia            30.0
Sequoiadendron     35.0
Styphnolobium      10.0
Taxodium           35.0
Taxus              13.0
Tilia              20.0
Ulmus              15.0
Zelkova            30.0

In [12]:
import numpy as np

x = np.arange(10)

array([ 2,  3,  0,  1,  6,  7,  4,  5, 10, 11])

In [19]:
x = np.array([[1,2,3],
    [4,5,6]])

y = np.array([
    1,
    2
]).reshape((-1,1))

In [25]:
a = y*x
a

array([[ 1,  2,  3],
       [ 8, 10, 12]])

In [27]:
(y*x).sum(axis=1)

array([ 6, 30])

In [10]:
tree.ESPECE.value_counts().sort_index()

araucana           1
atlantica          2
australis          1
baccata            2
bignonioides       1
biloba             5
bungeana           1
cappadocicum       1
carpinifolia       4
colurna            3
coulteri           1
decurrens          1
dioicus            1
distichum          3
excelsior          1
fraxinifolia       2
giganteum          5
giraldii           1
glutinosa          1
grandiflora        1
hippocastanum      3
ilex               1
involucrata        1
japonicum          1
kaki               2
libanii            2
monspessulanum     1
nigra              3
nigra laricio      1
opalus             1
orientalis         8
papyrifera         1
petraea            2
pomifera           1
pseudoacacia       1
sempervirens       1
serrata            1
stenoptera         1
suber              1
sylvatica          8
tomentosa          2
tulipifera         2
ulmoides           1
virginiana         2
x acerifolia      11
Name: ESPECE, dtype: int64

In [11]:
tree.ARRONDISSEMENT.value_counts().sort_index()

3      1
4      1
5      2
6      1
7      3
8      5
9      1
11     1
12    29
13     2
14     3
15     1
16    36
17     1
18     1
19     6
20     3
Name: ARRONDISSEMENT, dtype: int64